services:
  speaches:
    extends:
      file: compose.yaml
      service: speaches
    build:
      dockerfile: Dockerfile.rocm
      args:
        BASE_IMAGE: rocm/pytorch:rocm6.3.4_ubuntu24.04_py3.12_pytorch_release_2.6.0
    volumes:
      - hf-hub-cache:/root/.cache/huggingface/hub
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    ipc: host
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
      - render
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
      - GPU_MAX_ALLOC_PERCENT=100
volumes:
  hf-hub-cache:
